[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wordclock-controller"
version = "1.1.0"
description = "Advanced german word clock controller"
authors = [
  { name = "Your Name", email = "you@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.7"

dependencies = [
    "ntplib>=0.3.4",
    "rpi-ws281x>=4.2.6",
    "RPi.GPIO>=0.7.0",
    "smbus2>=0.4.1",
    "gpiozero>=1.5.1"
]

[project.optional-dependencies]
dev = [
  "black>=24.2.0",
  "flake8>=7.0.0",
  "mypy>=1.8.0"
]

[project.scripts]
wcctrl = "wcctrl.app_controller:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
